---
Sex:
    - male:
        Title:
            - Col.:
                percentages_columns:
                - Age
                - Fare
            - Dr.:
                percentages_columns:
                - Age
                - Fare
            - Master.:
                percentages_columns:
                - Pclass
                - [SibSp, Parch]
            - Mr.:
                percentages_columns:
                - Pclass
                - [SibSp, Parch]
            - Rev.:
                percentages_columns:
                - Title
    - female:
        Pclass:
            - 1:
                percentages_columns:
                - Sex
            - 2:
                percentages_columns:
                - Sex
            - 3:
                percentages_columns:
                - [SibSp, Parch]
                - Fare
                - Embarked
